import type { cardCertificate } from "../types/cardCertificate";

export const Certificates: cardCertificate[] = [
  {
    id: 1,
    courseName: "Universidad Desarrollo WebFrontEnd Web Developer!",
    platform: "Udemy",
    logo: "/assets/img/logos/Udemy-Logo.png",
    instructor: "Global Mentoring Ing. Ubaldo Acosta",
    completionDate: "2024-11-01",
    duration: "30.5 horas",
    skills: ["HTML", "CSS", "JavaScript"],
    pdfUrl: "/assets/certificates/UC-a4da7b5e-ea0f-4efe-aeef-3ddd45c71118.pdf",
  },
  {
    id: 2,
    courseName:
      "Aprende HTML5 y CSS3 de forma práctica [semantica, accesibilidad, responsive, flexbox, grid, menús]",
    platform: "Udemy",
    logo: "/assets/img/logos/Udemy-Logo.png",
    instructor: "Disco Duro de Roer",
    completionDate: "2025-01-29",
    duration: "21.5 horas",
    skills: [
      "HTML5 Semántico",
      "CSS3 Avanzado",
      "Responsive Design",
      "Flexbox & Grid",
      "Accesibilidad Web",
    ],
    pdfUrl: "/assets/certificates/UC-0f01d65f-dd50-46af-aa8f-3016d6f2db42.pdf",
  },
  {
    id: 3,
    courseName: "Universidad JavaScript - De Cero a Experto JavaScript!",
    platform: "Udemy",
    logo: "/assets/img/logos/Udemy-Logo.png",
    instructor: "Global Mentoring Ing. Ubaldo Acosta",
    completionDate: "2025-04-29",
    duration: "44.5 horas",
    skills: [
      "JavaScript Avanzado",
      "POO en JavaScript",
      "Async/Await",
      "Manipulación del DOM",
      "ES6+",
    ],
    pdfUrl: "/assets/certificates/UC-ae3709b8-6ce1-4975-8fc1-f7d3588699f7.pdf",
  },
  {
    id: 4,
    courseName: "Curso profesional de Git",
    platform: "Código Facilito",
    logo: "/assets/img/logos/Codigo-Facilito-logo.png",
    instructor: "Código Facilito",
    completionDate: "2025-05-26",
    duration: "3.4 horas",
    skills: [
      "Git & GitHub",
      "Control de Versiones",
      "Branching & Merging",
      "Resolución de Conflictos",
    ],
    pdfUrl: "/assets/certificates/Certificado-Curso-profesional-de-Git.pdf",
  },
  {
    id: 5,
    courseName: "Curso profesional de JavaScript",
    platform: "Código Facilito",
    logo: "/assets/img/logos/Codigo-Facilito-logo.png",
    instructor: "Código Facilito",
    completionDate: "2025-05-28",
    duration: "8.5 horas",
    skills: [
      "JavaScript ES6+",
      "POO Avanzada",
      "Promesas & Async",
      "Módulos ES6",
      "Regex",
    ],
    pdfUrl:
      "/assets/certificates/Certificado-Curso-profesional-de-JavaScript.pdf",
  },
  {
    id: 6,
    courseName: "Curso de Visual Studio Code y GitHub Copilot",
    platform: "Código Facilito",
    logo: "/assets/img/logos/Codigo-Facilito-logo.png",
    instructor: "Código Facilito",
    completionDate: "2025-05-29",
    duration: "3.21 horas",
    skills: [
      "VS Code Profesional",
      "GitHub Copilot",
      "IA en Desarrollo",
      "Debugging",
    ],
    pdfUrl:
      "/assets/certificates/Certificado-Curso-de-Visual-Studio-Code-y-GitHub-Copilot.pdf",
  },
  {
    id: 7,
    courseName: "Curso Profesional de Angular",
    platform: "Código Facilito",
    logo: "/assets/img/logos/Codigo-Facilito-logo.png",
    instructor: "Código Facilito",
    completionDate: "2025-05-29",
    duration: "5.32 horas",
    skills: [
      "Angular Framework",
      "Componentes & Directivas",
      "Routing",
      "Formularios Reactivos",
      "RxJS",
    ],
    pdfUrl: "/assets/certificates/Certificado-Curso-Profesional-de-Angular.pdf",
  },
  {
    id: 8,
    courseName: "Curso de Tailwind v4",
    platform: "Código Facilito",
    logo: "/assets/img/logos/Codigo-Facilito-logo.png",
    instructor: "Código Facilito",
    completionDate: "2025-11-06",
    duration: "4.32 horas",
    skills: [
      "Tailwind CSS",
      "Utility First",
      "Design System",
      "Responsive Design",
      "Dark Mode",
      "Animaciones con Tailwind",
    ],
    pdfUrl: "/assets/certificates/Certificado-Curso-de-Tailwind-v4.pdf",
  },
  {
    id: 9,
    courseName: "Ruta de fundamentos de React",
    platform: "Código Facilito",
    logo: "/assets/img/logos/Codigo-Facilito-logo.png",
    instructor: "Código Facilito",
    completionDate: "2025-11-09",
    duration: "9 semanas",
    skills: [
      "React Fundamentals",
      "JSX",
      "Componentes y Props",
      "Estado y Ciclo de Vida",
      "Hooks (useState, useEffect)",
      "Renderizado Condicional",
      "Renderizado de Listas",
    ],
    pdfUrl: "/assets/certificates/Certificado-Ruta-de-fundamentos-de-React.pdf",
  },
];
